# Sample .travis.yml for R projects

language: R
sudo: false
cache: packages

env:
  matrix:
    - RVERSION=release

branches:
  only:
    - master

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
