# Sample .travis.yml for R projects

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

branches:
  only:
    - master

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
